# Generated by Django 5.2.15 on 2026-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(help_text='OPIS Truckstop Identification Number')),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('rack_id', models.IntegerField(help_text='Rack ID')),
                ('retail_price', models.DecimalField(decimal_places=8, help_text='Retail Price', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=8, help_text='Latitude', max_digits=12)),
                ('long', models.DecimalField(decimal_places=8, help_text='Longitude', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StateCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=8, help_text='Latitude', max_digits=12)),
                ('long', models.DecimalField(decimal_places=8, help_text='Longitude', max_digits=12)),
            ],
        ),
    ]
